import { createElement } from 'lwc';
import CustomWidgetComponent from 'c/customWidgetComponent';

describe('c-custom-widget-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });
    
    test('test input entered from UI',()=>{
        const element = createElement('c-custom-widget-component', {
            is: CustomWidgetComponent
        });

        const input = element.shadowRoot.querySelector('lightning-input')
        const inputButton = element.shadowRoot.querySelector('lightning-button').getAttribute("disabled")
        
        input.value = '{}{'
        input.dispatchEvent(new CustomEvent('change'))
        return Promise.resolve().then(()=>{
            expect(inputButton.textContent).toBe(true)
        })
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-custom-widget-component', {
            is: CustomWidgetComponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});